title: Migración Interna, Tierras altas
email: fundacion@aru.org.bo
description: 
permalink: ':title/'
baseurl: "https://arufoundation.github.io/oim-aru/" # the subpath of your site, e.g. /blog
url: "https://arufoundation.github.io/oim-aru/" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Proyecto OIM-ARU # add your name
author-pic: logoaru.jpg
about-author: La Fundación Aru es un instituto de investigación de políticas públicas sin fines de lucro, independiente y plural. Su compromiso es producir y promover investigación local aplicada de alta calidad a partir de herramientas globales, que permita informar e influir en el debate sobre políticas públicas para incentivar la decisión en políticas públicas a partir de la evidencia científica. Creemos que las políticas más efectivas - aquellas que fomentan sociedades más vibrantes, sanas y cohesionadas y proporcionan oportunidades a las personas para construir mejores vidas - están basadas en el entendimiento de las realidades locales.

# Contact links
email: fundacion@aru.org.bo
phone: (591) 22004492
website: www.aru.org.bo
github: arufoundation # Add your Github handle
twitter: '@AruFoundation' # Add your Twitter handle
facebook: FundacionARU

# Newsletter
mailchimp: fundacion@aru.org.bo
# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
