title: Migración Interna, Tierras altas
email: fundacion@aru.org.bo
description: 
permalink: ':title/'
baseurl: "https://arufoundation.github.io/oim-aru/" # the subpath of your site, e.g. /blog
url: "https://arufoundation.github.io/oim-aru/" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Proyecto OIM-ARU # add your name
author-pic: logoaru.jpg
about-author: Las estadísticas disponibles sobre migración interna en Bolivia revelan una elevada movilidad de las personas entre regiones, entre departamentos y entre municipios. Por ejemplo, más 1.3 millones de personas cambiaron de residencia de un departamento a otro en el periodo 2007 a 2012 según información del último censo de población y vivienda. Las tasas de migración neta inter municipal sugieren grandes variaciones en la movilidad observada a nivel local. Existen municipios “grandes” como Santa Cruz de la Sierra que recibieron hasta 89 mil personas de otros municipios durante este periodo, así como, existen municipios “pequeños” que recibieron menos de 10 personas. 
En cambio, existen otros municipios que se habrían convertido en “expulsores” de población. Entre las ciudades capitales que cuentan con más emigrantes, destaca el municipio de La Paz cuyo volumen de personas que “salieron” sobre pasó las 69 mil lo que equivale a un 40% del total de su población. Como es de esperar, la salida de personas es más notoria en los territorios pequeños en los cuales la población emigrante puede llegar a representar hasta el 100% de su población total.
A pesar de la evidencia respecto a la magnitud de estos movimientos, es poco lo que se conoce sobre el origen y las causas de la migración interna. De manera particular, resulta de interés determinar hasta qué punto las migraciones se deben a decisiones de las personas lo que refuerza su derecho a migrar y determinar. Alternativamente, se debe determinar bajo qué circunstancias la migración podría resultar de factores ajenos a la voluntad de las personas resultando en una suerte de “migración forzada”. En el contexto del presente estudio, interesa determinar cuándo y bajo qué circunstancias los fenómenos asociados al cambio climático podrían estar influyendo en dicha decisión. 
El estudio responde a dos problemas fundamentales. Por un lado, existen poblaciones pobres en situación de extrema vulnerabilidad por su exposición a un conjunto de amenazas climáticas que incluyen, principalmente, sequía, granizadas y heladas. Por otro, existe una débil capacidad de respuesta de las instituciones (municipios y comunidades organizadas) a nivel local. Ambos fenómenos – elevada vulnerabilidad y reducida capacidad de respuesta – estarían generando un flujo de emigrantes que va más allá de la “tendencia natural”. En concreto, los efectos del cambio climático estarían determinando una suerte de “expulsión” de las poblaciones afectadas desde sus lugares de origen, un fenómeno que iría más allá de su capacidad de “decidir” migrar. 

# Contact links
email: fundacion@aru.org.bo
phone: (591) 22004492
website: www.aru.org.bo
github: arufoundation # Add your Github handle
twitter: '@AruFoundation' # Add your Twitter handle
facebook: FundacionARU

# Newsletter
mailchimp: fundacion@aru.org.bo
# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
